development:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: sys
  password: system

test:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: sys
  password: system

production:
  adapter: oracle_enhanced
  host: localhost
  port: 1521
  database: xe
  username: sys
  password: system
